name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'Client/YCrispBiscuit-Tools-Client/**'  # 只有前端代码变更时才触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Client/YCrispBiscuit-Tools-Client/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      working-directory: Client/YCrispBiscuit-Tools-Client
      
    - name: Build
      run: npm run build
      working-directory: Client/YCrispBiscuit-Tools-Client
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: Client/YCrispBiscuit-Tools-Client/dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4